<a href="https://colab.research.google.com/github/vinay10949/AnalyticsAndML/blob/master/ReinforcementLearning/OptimizingBusinessProcessUsingQLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

gamma=0.75
alpha=0.9

In [0]:
# PART 1 - DEFINING THE ENVIRONMENT
# Defining the states

location_to_state = {'A':'0','B':'1','C':'2','D':'3','E':'4','F':'5','G':'6','H':'7','I':'8','J':'9','K':'10','L':'11'}

# Defining the actions
actions = [0,1,2,3,4,5,6,7,8,9,10,11]

In [0]:
#Rewards
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
[1,0,1,0,0,1,0,0,0,0,0,0],
[0,1,0,0,0,0,1,0,0,0,0,0],
[0,0,0,0,0,0,0,1,0,0,0,0],
[0,0,0,0,0,0,0,0,1,0,0,0],
[0,1,0,0,0,0,0,0,0,1,0,0],
[0,0,1,0,0,0,1,1,0,0,0,0],
[0,0,0,1,0,0,1,0,0,0,0,1],
[0,0,0,0,1,0,0,0,0,1,0,0],
[0,0,0,0,0,1,0,0,1,0,1,0],
[0,0,0,0,0,0,0,0,0,1,0,1],
[0,0,0,0,0,0,0,1,0,0,1,0]])

In [0]:
Q = np.array(np.zeros([12,12]))

# Implementing the Q-Learning process
for i in range(1000):
  current_state = np.random.randint(0,12)
  playable_actions = []
  for j in range(12):
    if R[current_state, j] > 0:
      playable_actions.append(j)
  next_state = np.random.choice(playable_actions)
  #Temporal difference  =Q(Currentstate,action) -
  TD = R[current_state, next_state] + gamma*Q[next_state, np.argmax(Q[next_state,])]- Q[current_state, next_state]
  Q[current_state, next_state] = Q[current_state, next_state] + alpha*TD

In [0]:
print("Q-Values:")
print(Q.astype(int))

Q-Values:
[[0 3 0 0 0 0 0 0 0 0 0 0]
 [3 0 3 0 0 3 0 0 0 0 0 0]
 [0 3 0 0 0 0 3 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0]
 [0 3 0 0 0 0 0 0 0 3 0 0]
 [0 0 3 0 0 0 3 3 0 0 0 0]
 [0 0 0 3 0 0 3 0 0 0 0 3]
 [0 0 0 0 3 0 0 0 0 3 0 0]
 [0 0 0 0 0 3 0 0 3 0 3 0]
 [0 0 0 0 0 0 0 0 0 3 0 3]
 [0 0 0 0 0 0 0 3 0 0 3 0]]


In [0]:

# Making a mapping from the states to the locations
state_to_location = {state: location for location, state in location_to_state.items()}
state_to_location

{'0': 'A',
 '1': 'B',
 '10': 'K',
 '11': 'L',
 '2': 'C',
 '3': 'D',
 '4': 'E',
 '5': 'F',
 '6': 'G',
 '7': 'H',
 '8': 'I',
 '9': 'J'}

In [0]:
# Making the final function that will return the optimal route
def route(starting_location, ending_location):
	route = [starting_location]
	next_location = starting_location
	while (next_location != ending_location):
		starting_state = location_to_state[starting_location]
		starting_state=int(starting_state)
		next_state = np.argmax(Q[starting_state,])
		next_location = state_to_location[next_state]
		route.append(next_location)
		starting_location = next_location
	return route

In [0]:
# Making the final function that will return the route
def route(starting_location, ending_location):
	R_new = np.copy(R)
	ending_state = int(location_to_state[ending_location])
	R_new[ending_state, ending_state] = 1000
	Q = np.array(np.zeros([12,12]))
	for i in range(1000):
		current_state = np.random.randint(0,12)
		playable_actions = []
		for j in range(12):
			if R_new[current_state, j] > 0:
				  playable_actions.append(j)
		next_state = np.random.choice(playable_actions)
		TD = R_new[current_state, next_state]+ gamma * Q[next_state, np.argmax(Q[next_state,])]- Q[current_state, next_state]
		Q[current_state, next_state] = Q[current_state, next_state] + alpha * TD
	route = [starting_location]
	next_location = starting_location
	while (next_location != ending_location):
		starting_state = int(location_to_state[starting_location])
		next_state = np.argmax(Q[starting_state,])
		next_location = state_to_location[str(next_state)]
		route.append(next_location)
		starting_location = next_location
	return route

In [0]:
print('Route:')
route('E', 'G')

Route:


['E', 'I', 'J', 'F', 'B', 'C', 'G']

In [0]:
#Making the final function that returns the optimal route
def best_route(starting_location, intermediary_location, ending_location):
  return route(starting_location, intermediary_location)+ route(intermediary_location, ending_location)[1:]

In [0]:
print('Best Route:',best_route('E', 'K','G'))


Best Route: ['E', 'I', 'J', 'K', 'L', 'H', 'G']
